package fantasy.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanContainer;
import com.vaadin.data.util.ObjectProperty;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

import fantasy.domain.Round;
import fantasy.domain.RoundTotal;

import java.util.List;
import fantasy.domain.Game;
import javax.swing.JLabel;
import fantasy.domain.Team;
public class ResultsView extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ResultsView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		updateResultsView();
		
		
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new VerticalLayout();
	}
	
	public void updateResultsView(){
		mainLayout.removeAllComponents();
		List<Round> rounds = Round.findAllRounds();
		for (Round round : rounds) {
			Label roundLabel = new Label(round.getName());
			mainLayout.addComponent(roundLabel);
			
			for(Game game : round.getGames()){
				makeGameTable(round, game);
			}
			
			
		}
	}
	
	private void makeGameTable(Round round, Game game){
		Table gameTable = new Table();
		gameTable.setPageLength(2);
		RoundTotal homeRoundTotal = getCurrentRoundTotal(round, game.getHomeTeam());
		RoundTotal awayRoundTotal = getCurrentRoundTotal(round, game.getAwayTeam());
		gameTable.setCaption(game.getHomeTeam().getName() + " VS "+ game.getAwayTeam().getName());
		if(homeRoundTotal == null || awayRoundTotal == null) return;
		
		Long homeRoundTotalId = homeRoundTotal.getId();
		Long awayRoundTotalId = awayRoundTotal.getId();
		
		BeanContainer<Long, RoundTotal> totalsContainer = new BeanContainer<Long, RoundTotal>(RoundTotal.class);
		totalsContainer.setBeanIdProperty("id");
		
		totalsContainer.addBean(homeRoundTotal);
		totalsContainer.addBean(awayRoundTotal);
		
		
		gameTable.setContainerDataSource(totalsContainer);
		totalsContainer.addNestedContainerProperty("team.name");
		Object[] visibleColumns = new Object[] {"team.name","points", "lpPoints","rebounds", "lpRebounds", "assists", "lpAssists", 
				"blocks", "lpBlocks", "steals", "lpSteals", "turnovers", "lpTurnovers", "ftMade", "lpFtMade", "threePointsMade",
				"lpThreePointsMade", "fgMade", "fgAttempts","fieldGoalPercentage", "lpFieldGoalPercentage", "totalPoints"};
		gameTable.setVisibleColumns(visibleColumns);
		String[] columnHeaders = new String[]{"Teams", "Pts", "LP-Pts", "Reb", "LP-Reb", "Ass", "LP-Ass", "Blk", "LP-Blk", "Stl", "LP-Stl",
												"To", "LP-To", "Ftm", "LP-Ftm", "3Fgm", "LP-3Fgm", "Fgm", "Fga", "Fg%", "LP-Fg%", "Total points"};
		gameTable.setColumnHeaders(columnHeaders);
		mainLayout.addComponent(gameTable);
		
	}
	
	private RoundTotal getCurrentRoundTotal(Round round, Team team){
		RoundTotal currentRoundTotal = null;
		for(RoundTotal roundTotal: team.getRoundTotals()){
			if(roundTotal.getRound().equals(round)){
				currentRoundTotal = roundTotal;
				break;
			}
		}
		return currentRoundTotal;
	}
	
}
