package fantasy.web;

import java.text.SimpleDateFormat;
import java.util.List;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanContainer;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

import fantasy.domain.Game;
import fantasy.domain.Round;
import fantasy.domain.RoundTotal;
import fantasy.domain.Team;
import java.util.Date;
public class ResultsView extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ResultsView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		// TODO add user code here
		updateResultsView();
		
		
	}

	public void updateResultsView(){
		mainLayout.removeAllComponents();
		List<Round> rounds = Round.findAllRounds();
		for (Round round : rounds) {
			String startDate = formatDate(round.getStartDate());
			String endDate = formatDate(round.getEndDate());
			Label roundLabel = new Label(round.getName() + " " + startDate + " - " + endDate);
			roundLabel.setStyleName("roundHeader");
			roundLabel.setWidth("-1px");
			mainLayout.addComponent(roundLabel);
			mainLayout.setComponentAlignment(roundLabel, new Alignment(Alignment.TOP_CENTER.getBitMask()));
			
			for(Game game : round.getGames()){
				makeGameTable(round, game);
			}
			
			
		}
	}
	
	private String formatDate(Date date){
		SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy");
		return format.format(date);
	}
	
	private void makeGameTable(Round round, Game game){
		Table gameTable = new Table();
		gameTable.setPageLength(2);
		
		RoundTotal homeRoundTotal = getCurrentRoundTotal(round, game.getHomeTeam());
		RoundTotal awayRoundTotal = getCurrentRoundTotal(round, game.getAwayTeam());
		gameTable.setCaption(game.getHomeTeam().getName() + " VS "+ game.getAwayTeam().getName());
		if(homeRoundTotal == null || awayRoundTotal == null) return;
		
		
		
		BeanContainer<Long, RoundTotal> totalsContainer = new BeanContainer<Long, RoundTotal>(RoundTotal.class);
		totalsContainer.setBeanIdProperty("id");
		
		totalsContainer.addBean(homeRoundTotal);
		totalsContainer.addBean(awayRoundTotal);
		
		
		gameTable.setContainerDataSource(totalsContainer);
		totalsContainer.addNestedContainerProperty("team.name");
		Object[] visibleColumns = new Object[] {"team.name","points", "lpPoints","rebounds", "lpRebounds", "assists", "lpAssists", 
				"blocks", "lpBlocks", "steals", "lpSteals", "turnovers", "lpTurnovers", "ftMade", "lpFtMade", "threePointsMade",
				"lpThreePointsMade", "fgMade", "fgAttempts","fieldGoalPercentage", "lpFieldGoalPercentage", "totalPoints"};
		gameTable.setVisibleColumns(visibleColumns);
		String[] columnHeaders = new String[]{"Teams", "Pts", "LP-Pts", "Reb", "LP-Reb", "Ass", "LP-Ass", "Blk", "LP-Blk", "Stl", "LP-Stl",
												"To", "LP-To", "Ftm", "LP-Ftm", "3Fgm", "LP-3Fgm", "Fgm", "Fga", "Fg%", "LP-Fg%", "Total points"};
		gameTable.setColumnHeaders(columnHeaders);
		mainLayout.addComponent(gameTable);
		mainLayout.setComponentAlignment(gameTable, new Alignment(Alignment.TOP_CENTER.getBitMask()));
		
	}
	
	private RoundTotal getCurrentRoundTotal(Round round, Team team){
		RoundTotal currentRoundTotal = null;
		for(RoundTotal roundTotal: team.getRoundTotals()){
			if(roundTotal.getRound().equals(round)){
				currentRoundTotal = roundTotal;
				break;
			}
		}
		return currentRoundTotal;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		return mainLayout;
	}
	
}
