package fantasy.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.TabSheet.SelectedTabChangeEvent;
import com.vaadin.ui.TabSheet.SelectedTabChangeListener;

public class TabPanel extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private TabSheet tabSheet_1;
	@AutoGenerated
	private TeamsView teamsView_1;
	@AutoGenerated
	private FantasyEntityManagerView fantasyEntityManagerView_1;

	

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TabPanel() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		
		//update TeamsView when loading it
		tabSheet_1.addListener(new SelectedTabChangeListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void selectedTabChange(SelectedTabChangeEvent event) {
				
				if(tabSheet_1.getSelectedTab() instanceof TeamsView){
					teamsView_1.updateTeamsView();
				}
			}
		});
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		mainLayout.addComponent(tabSheet_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setImmediate(true);
		tabSheet_1.setWidth("1000px");
		tabSheet_1.setHeight("1000px");
		
		// fantasyEntityManagerView_1
		fantasyEntityManagerView_1 = new FantasyEntityManagerView();
		fantasyEntityManagerView_1.setImmediate(false);
		fantasyEntityManagerView_1.setWidth("1000px");
		fantasyEntityManagerView_1.setHeight("1000px");
		tabSheet_1.addTab(fantasyEntityManagerView_1, "Admin", null);
		
		// teamsView_1
		teamsView_1 = new TeamsView();
		teamsView_1.setImmediate(false);
		teamsView_1.setWidth("1000px");
		teamsView_1.setHeight("1000px");
		tabSheet_1.addTab(teamsView_1, "Teams", null);
		
		return tabSheet_1;
	}

}
