package fantasy.web;

import org.joda.time.LocalDate;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;

import fantasy.domain.scraping.DataScraper;

public class UpdateView extends CustomComponent {

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private Button updateButton;
	@AutoGenerated
	private PopupDateField popupDateField_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public UpdateView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		updateButton.addListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				DataScraper scraper = new DataScraper();
				System.out.println(scraper.updateStats(new LocalDate(2011, 12, 25)));
				
			}
		});
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// popupDateField_1
		popupDateField_1 = new PopupDateField();
		popupDateField_1.setImmediate(false);
		popupDateField_1.setWidth("-1px");
		popupDateField_1.setHeight("-1px");
		popupDateField_1.setInvalidAllowed(false);
		mainLayout.addComponent(popupDateField_1);
		
		// updateButton
		updateButton = new Button();
		updateButton.setCaption("Update Database");
		updateButton.setImmediate(true);
		updateButton.setWidth("-1px");
		updateButton.setHeight("-1px");
		mainLayout.addComponent(updateButton);
		mainLayout.setExpandRatio(updateButton, 1.0f);
		
		return mainLayout;
	}

}
