package fantasy.web.authentication;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ExternalResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import fantasy.web.TabPanel;
import fantasy.web.FantasyApplication;

public class LoginForm extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	
	@AutoGenerated
	private Button loginButton;
	@AutoGenerated
	private PasswordField passwordField;
	@AutoGenerated
	private TextField userNameField;








	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public LoginForm() {
		buildMainLayout();
		setCompositionRoot(mainLayout);


		loginButton.addListener ( new Button.ClickListener()
        {
            public void buttonClick ( Button.ClickEvent event )
            {
            	final TabPanel parentTabPanel = (TabPanel)getParent().getParent().getParent();
            	final Window appWindow =  (Window)getParent().getParent().getParent().getParent().getParent().getParent();
            	try
                {
                    FantasyApplication.getInstance ().authenticate((String)userNameField.getValue (), (String)passwordField.getValue ());
                    
                    parentTabPanel.refreshAfterLogin();
                    userNameField.setValue("");
                    passwordField.setValue("");
                    //parentWindow.open( new ExternalResource (FantasyApplication.getInstance ().getURL ()));
                }
                catch ( Exception e )
                {
                	appWindow.showNotification ( "Login Failed.\nWrong username or password");
                }
            }
        });
	
	}
	
	
	
	
	
	
	
	

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// userNameField
		userNameField = new TextField();
		userNameField.setCaption("Username");
		userNameField.setImmediate(false);
		userNameField.setWidth("-1px");
		userNameField.setHeight("-1px");
		userNameField.setSecret(false);
		mainLayout.addComponent(userNameField);
		mainLayout.setComponentAlignment(userNameField, new Alignment(48));
		
		// passwordField
		passwordField = new PasswordField();
		passwordField.setCaption("Password");
		passwordField.setImmediate(false);
		passwordField.setWidth("-1px");
		passwordField.setHeight("-1px");
		passwordField.setNullRepresentation("\"\"");
		mainLayout.addComponent(passwordField);
		mainLayout.setComponentAlignment(passwordField, new Alignment(48));
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		mainLayout.setExpandRatio(horizontalLayout_1, 1.0f);
		mainLayout.setComponentAlignment(horizontalLayout_1, new Alignment(48));
		
		return mainLayout;
	}








	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// loginButton
		loginButton = new Button();
		loginButton.setCaption("Login");
		loginButton.setImmediate(true);
		loginButton.setWidth("-1px");
		loginButton.setHeight("-1px");
		horizontalLayout_1.addComponent(loginButton);
		
	
		return horizontalLayout_1;
	}

}
