package fantasy.web.authentication;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.terminal.ExternalResource;
import fantasy.web.FantasyApplication;
import fantasy.web.FantasyWindow;

public class LoginForm extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button visitorButton;
	@AutoGenerated
	private Button loginButton;
	@AutoGenerated
	private PasswordField passwordField;
	@AutoGenerated
	private TextField userNameField;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public LoginForm() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		loginButton.addListener ( new Button.ClickListener()
        {
            public void buttonClick ( Button.ClickEvent event )
            {
                Window parentWindow = (Window)getParent().getParent();
            	try
                {
                    FantasyApplication.getInstance ().authenticate((String)userNameField.getValue (), (String)passwordField.getValue ());
                    
                    parentWindow.open ( new ExternalResource (FantasyApplication.getInstance ().getURL ()));
                }
                catch ( Exception e )
                {
                    parentWindow.showNotification ( e.toString ());
                }
            }
        });
	}
	
	
	
	
	
	
	

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// userNameField
		userNameField = new TextField();
		userNameField.setCaption("Username");
		userNameField.setImmediate(false);
		userNameField.setWidth("-1px");
		userNameField.setHeight("-1px");
		userNameField.setSecret(false);
		mainLayout.addComponent(userNameField);
		mainLayout.setComponentAlignment(userNameField, new Alignment(20));
		
		// passwordField
		passwordField = new PasswordField();
		passwordField.setCaption("Password");
		passwordField.setImmediate(false);
		passwordField.setWidth("-1px");
		passwordField.setHeight("-1px");
		passwordField.setNullRepresentation("\"\"");
		mainLayout.addComponent(passwordField);
		mainLayout.setExpandRatio(passwordField, 1.0f);
		mainLayout.setComponentAlignment(passwordField, new Alignment(20));
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// loginButton
		loginButton = new Button();
		loginButton.setCaption("Login");
		loginButton.setImmediate(false);
		loginButton.setWidth("-1px");
		loginButton.setHeight("-1px");
		horizontalLayout_1.addComponent(loginButton);
		
		// visitorButton
		visitorButton = new Button();
		visitorButton.setCaption("Login as visitor");
		visitorButton.setImmediate(false);
		visitorButton.setWidth("-1px");
		visitorButton.setHeight("-1px");
		horizontalLayout_1.addComponent(visitorButton);
		
		return horizontalLayout_1;
	}

}
