package fantasy.web.ui;

import java.util.Arrays;

import com.vaadin.addon.jpacontainer.JPAContainerFactory;
import com.vaadin.addon.jpacontainer.JPAContainerItem;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;

import fantasy.domain.Player;
import fantasy.domain.Team;
import fantasy.web.AutomaticEntityForm;
public class EntityTab extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private TabSheet tabSheet_1;
	@AutoGenerated
	private EntityTable playerTable;
	@AutoGenerated
	private EntityTable teamTable;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public EntityTab() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
////		teamTable.init(Team.class, 
////				new Object[] {"name", "players"}, new TeamEditor());
////		playerTable.init(Player.class, 
////				new Object[] {"firstName", "lastName", "team"},
////				new PlayerEditor());
////		AutomaticEntityForm<Player> playerForm = new AutomaticEntityForm<Player>(Player.class);
////		playerForm.setHeight("100.0%");
////		playerForm.setImmediate(false);
////		playerForm.setWidth("100.0%");
//		tabSheet_1.addTab(playerForm, "Form");
		AutomaticEntityForm<Team> aef = new AutomaticEntityForm<Team>(Team.class);
		aef.setItemDataSource((new BeanItem<Team>(new Team())));
		tabSheet_1.addTab(aef, "form");
		
		
	}
		
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		mainLayout.addComponent(tabSheet_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setImmediate(true);
		tabSheet_1.setWidth("100.0%");
		tabSheet_1.setHeight("100.0%");
		
		
		
		return tabSheet_1;
	}

}
