package fantasy.web.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

import fantasy.domain.Rules;
public class RulesView extends CustomComponent implements ContentUpdateable {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Label textContent;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 1L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public RulesView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		textContent.setContentMode(Label.CONTENT_XHTML);
	}
	
	public void updateContent(){
		if(Rules.countRuleses()!= 0){
			//show first rules entity in view
			Rules rules = Rules.findRulesEntries(0, 1).get(0);
		
			textContent.setValue(rules.getText());
			
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// textContent
		textContent = new Label();
		textContent.setImmediate(false);
		textContent.setWidth("100.0%");
		textContent.setHeight("-1px");
		textContent.setValue("Label");
		mainLayout.addComponent(textContent);
		mainLayout.setComponentAlignment(textContent, new Alignment(20));
		
		return mainLayout;
	}

}
