// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fantasy.domain;

import fantasy.domain.AdminSwitchDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AdminSwitchIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AdminSwitchIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AdminSwitchIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: AdminSwitchIntegrationTest: @Transactional;
    
    @Autowired
    private AdminSwitchDataOnDemand AdminSwitchIntegrationTest.dod;
    
    @Test
    public void AdminSwitchIntegrationTest.testCountAdminSwitches() {
        org.junit.Assert.assertNotNull("Data on demand for 'AdminSwitch' failed to initialize correctly", dod.getRandomAdminSwitch());
        long count = fantasy.domain.AdminSwitch.countAdminSwitches();
        org.junit.Assert.assertTrue("Counter for 'AdminSwitch' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AdminSwitchIntegrationTest.testFindAdminSwitch() {
        fantasy.domain.AdminSwitch obj = dod.getRandomAdminSwitch();
        org.junit.Assert.assertNotNull("Data on demand for 'AdminSwitch' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'AdminSwitch' failed to provide an identifier", id);
        obj = fantasy.domain.AdminSwitch.findAdminSwitch(id);
        org.junit.Assert.assertNotNull("Find method for 'AdminSwitch' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'AdminSwitch' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AdminSwitchIntegrationTest.testFindAllAdminSwitches() {
        org.junit.Assert.assertNotNull("Data on demand for 'AdminSwitch' failed to initialize correctly", dod.getRandomAdminSwitch());
        long count = fantasy.domain.AdminSwitch.countAdminSwitches();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'AdminSwitch', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<fantasy.domain.AdminSwitch> result = fantasy.domain.AdminSwitch.findAllAdminSwitches();
        org.junit.Assert.assertNotNull("Find all method for 'AdminSwitch' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'AdminSwitch' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AdminSwitchIntegrationTest.testFindAdminSwitchEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'AdminSwitch' failed to initialize correctly", dod.getRandomAdminSwitch());
        long count = fantasy.domain.AdminSwitch.countAdminSwitches();
        if (count > 20) count = 20;
        java.util.List<fantasy.domain.AdminSwitch> result = fantasy.domain.AdminSwitch.findAdminSwitchEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'AdminSwitch' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'AdminSwitch' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AdminSwitchIntegrationTest.testFlush() {
        fantasy.domain.AdminSwitch obj = dod.getRandomAdminSwitch();
        org.junit.Assert.assertNotNull("Data on demand for 'AdminSwitch' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'AdminSwitch' failed to provide an identifier", id);
        obj = fantasy.domain.AdminSwitch.findAdminSwitch(id);
        org.junit.Assert.assertNotNull("Find method for 'AdminSwitch' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAdminSwitch(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'AdminSwitch' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AdminSwitchIntegrationTest.testMerge() {
        fantasy.domain.AdminSwitch obj = dod.getRandomAdminSwitch();
        org.junit.Assert.assertNotNull("Data on demand for 'AdminSwitch' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'AdminSwitch' failed to provide an identifier", id);
        obj = fantasy.domain.AdminSwitch.findAdminSwitch(id);
        boolean modified =  dod.modifyAdminSwitch(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        fantasy.domain.AdminSwitch merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'AdminSwitch' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AdminSwitchIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'AdminSwitch' failed to initialize correctly", dod.getRandomAdminSwitch());
        fantasy.domain.AdminSwitch obj = dod.getNewTransientAdminSwitch(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'AdminSwitch' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'AdminSwitch' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'AdminSwitch' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AdminSwitchIntegrationTest.testRemove() {
        fantasy.domain.AdminSwitch obj = dod.getRandomAdminSwitch();
        org.junit.Assert.assertNotNull("Data on demand for 'AdminSwitch' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'AdminSwitch' failed to provide an identifier", id);
        obj = fantasy.domain.AdminSwitch.findAdminSwitch(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'AdminSwitch' with identifier '" + id + "'", fantasy.domain.AdminSwitch.findAdminSwitch(id));
    }
    
}
