// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fantasy.domain;

import fantasy.domain.News;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect NewsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: NewsDataOnDemand: @Component;
    
    private Random NewsDataOnDemand.rnd = new SecureRandom();
    
    private List<News> NewsDataOnDemand.data;
    
    public News NewsDataOnDemand.getNewTransientNews(int index) {
        News obj = new News();
        setText(obj, index);
        return obj;
    }
    
    public void NewsDataOnDemand.setText(News obj, int index) {
        String text = "_" + index;
        obj.setText(text);
    }
    
    public News NewsDataOnDemand.getSpecificNews(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        News obj = data.get(index);
        return News.findNews(obj.getId());
    }
    
    public News NewsDataOnDemand.getRandomNews() {
        init();
        News obj = data.get(rnd.nextInt(data.size()));
        return News.findNews(obj.getId());
    }
    
    public boolean NewsDataOnDemand.modifyNews(News obj) {
        return false;
    }
    
    public void NewsDataOnDemand.init() {
        data = News.findNewsEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'News' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<fantasy.domain.News>();
        for (int i = 0; i < 10; i++) {
            News obj = getNewTransientNews(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
