// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fantasy.domain;

import fantasy.domain.NewsDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect NewsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: NewsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: NewsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: NewsIntegrationTest: @Transactional;
    
    @Autowired
    private NewsDataOnDemand NewsIntegrationTest.dod;
    
    @Test
    public void NewsIntegrationTest.testCountNews() {
        org.junit.Assert.assertNotNull("Data on demand for 'News' failed to initialize correctly", dod.getRandomNews());
        long count = fantasy.domain.News.countNews();
        org.junit.Assert.assertTrue("Counter for 'News' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void NewsIntegrationTest.testFindNews() {
        fantasy.domain.News obj = dod.getRandomNews();
        org.junit.Assert.assertNotNull("Data on demand for 'News' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'News' failed to provide an identifier", id);
        obj = fantasy.domain.News.findNews(id);
        org.junit.Assert.assertNotNull("Find method for 'News' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'News' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void NewsIntegrationTest.testFindAllNews() {
        org.junit.Assert.assertNotNull("Data on demand for 'News' failed to initialize correctly", dod.getRandomNews());
        long count = fantasy.domain.News.countNews();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'News', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<fantasy.domain.News> result = fantasy.domain.News.findAllNews();
        org.junit.Assert.assertNotNull("Find all method for 'News' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'News' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void NewsIntegrationTest.testFindNewsEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'News' failed to initialize correctly", dod.getRandomNews());
        long count = fantasy.domain.News.countNews();
        if (count > 20) count = 20;
        java.util.List<fantasy.domain.News> result = fantasy.domain.News.findNewsEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'News' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'News' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void NewsIntegrationTest.testFlush() {
        fantasy.domain.News obj = dod.getRandomNews();
        org.junit.Assert.assertNotNull("Data on demand for 'News' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'News' failed to provide an identifier", id);
        obj = fantasy.domain.News.findNews(id);
        org.junit.Assert.assertNotNull("Find method for 'News' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyNews(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'News' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NewsIntegrationTest.testMerge() {
        fantasy.domain.News obj = dod.getRandomNews();
        org.junit.Assert.assertNotNull("Data on demand for 'News' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'News' failed to provide an identifier", id);
        obj = fantasy.domain.News.findNews(id);
        boolean modified =  dod.modifyNews(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        fantasy.domain.News merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'News' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NewsIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'News' failed to initialize correctly", dod.getRandomNews());
        fantasy.domain.News obj = dod.getNewTransientNews(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'News' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'News' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'News' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void NewsIntegrationTest.testRemove() {
        fantasy.domain.News obj = dod.getRandomNews();
        org.junit.Assert.assertNotNull("Data on demand for 'News' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'News' failed to provide an identifier", id);
        obj = fantasy.domain.News.findNews(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'News' with identifier '" + id + "'", fantasy.domain.News.findNews(id));
    }
    
}
