// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fantasy.domain;

import fantasy.domain.PlayerPosDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PlayerPosIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PlayerPosIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PlayerPosIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PlayerPosIntegrationTest: @Transactional;
    
    @Autowired
    private PlayerPosDataOnDemand PlayerPosIntegrationTest.dod;
    
    @Test
    public void PlayerPosIntegrationTest.testCountPlayerPoses() {
        org.junit.Assert.assertNotNull("Data on demand for 'PlayerPos' failed to initialize correctly", dod.getRandomPlayerPos());
        long count = fantasy.domain.PlayerPos.countPlayerPoses();
        org.junit.Assert.assertTrue("Counter for 'PlayerPos' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PlayerPosIntegrationTest.testFindPlayerPos() {
        fantasy.domain.PlayerPos obj = dod.getRandomPlayerPos();
        org.junit.Assert.assertNotNull("Data on demand for 'PlayerPos' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PlayerPos' failed to provide an identifier", id);
        obj = fantasy.domain.PlayerPos.findPlayerPos(id);
        org.junit.Assert.assertNotNull("Find method for 'PlayerPos' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'PlayerPos' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PlayerPosIntegrationTest.testFindAllPlayerPoses() {
        org.junit.Assert.assertNotNull("Data on demand for 'PlayerPos' failed to initialize correctly", dod.getRandomPlayerPos());
        long count = fantasy.domain.PlayerPos.countPlayerPoses();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'PlayerPos', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<fantasy.domain.PlayerPos> result = fantasy.domain.PlayerPos.findAllPlayerPoses();
        org.junit.Assert.assertNotNull("Find all method for 'PlayerPos' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'PlayerPos' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PlayerPosIntegrationTest.testFindPlayerPosEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'PlayerPos' failed to initialize correctly", dod.getRandomPlayerPos());
        long count = fantasy.domain.PlayerPos.countPlayerPoses();
        if (count > 20) count = 20;
        java.util.List<fantasy.domain.PlayerPos> result = fantasy.domain.PlayerPos.findPlayerPosEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'PlayerPos' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'PlayerPos' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PlayerPosIntegrationTest.testFlush() {
        fantasy.domain.PlayerPos obj = dod.getRandomPlayerPos();
        org.junit.Assert.assertNotNull("Data on demand for 'PlayerPos' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PlayerPos' failed to provide an identifier", id);
        obj = fantasy.domain.PlayerPos.findPlayerPos(id);
        org.junit.Assert.assertNotNull("Find method for 'PlayerPos' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPlayerPos(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'PlayerPos' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PlayerPosIntegrationTest.testMerge() {
        fantasy.domain.PlayerPos obj = dod.getRandomPlayerPos();
        org.junit.Assert.assertNotNull("Data on demand for 'PlayerPos' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PlayerPos' failed to provide an identifier", id);
        obj = fantasy.domain.PlayerPos.findPlayerPos(id);
        boolean modified =  dod.modifyPlayerPos(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        fantasy.domain.PlayerPos merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'PlayerPos' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PlayerPosIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'PlayerPos' failed to initialize correctly", dod.getRandomPlayerPos());
        fantasy.domain.PlayerPos obj = dod.getNewTransientPlayerPos(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'PlayerPos' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'PlayerPos' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'PlayerPos' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PlayerPosIntegrationTest.testRemove() {
        fantasy.domain.PlayerPos obj = dod.getRandomPlayerPos();
        org.junit.Assert.assertNotNull("Data on demand for 'PlayerPos' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PlayerPos' failed to provide an identifier", id);
        obj = fantasy.domain.PlayerPos.findPlayerPos(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'PlayerPos' with identifier '" + id + "'", fantasy.domain.PlayerPos.findPlayerPos(id));
    }
    
}
