// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fantasy.domain;

import fantasy.domain.RoundDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RoundIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RoundIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RoundIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: RoundIntegrationTest: @Transactional;
    
    @Autowired
    private RoundDataOnDemand RoundIntegrationTest.dod;
    
    @Test
    public void RoundIntegrationTest.testCountRounds() {
        org.junit.Assert.assertNotNull("Data on demand for 'Round' failed to initialize correctly", dod.getRandomRound());
        long count = fantasy.domain.Round.countRounds();
        org.junit.Assert.assertTrue("Counter for 'Round' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RoundIntegrationTest.testFindRound() {
        fantasy.domain.Round obj = dod.getRandomRound();
        org.junit.Assert.assertNotNull("Data on demand for 'Round' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Round' failed to provide an identifier", id);
        obj = fantasy.domain.Round.findRound(id);
        org.junit.Assert.assertNotNull("Find method for 'Round' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Round' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RoundIntegrationTest.testFindAllRounds() {
        org.junit.Assert.assertNotNull("Data on demand for 'Round' failed to initialize correctly", dod.getRandomRound());
        long count = fantasy.domain.Round.countRounds();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Round', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<fantasy.domain.Round> result = fantasy.domain.Round.findAllRounds();
        org.junit.Assert.assertNotNull("Find all method for 'Round' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Round' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RoundIntegrationTest.testFindRoundEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Round' failed to initialize correctly", dod.getRandomRound());
        long count = fantasy.domain.Round.countRounds();
        if (count > 20) count = 20;
        java.util.List<fantasy.domain.Round> result = fantasy.domain.Round.findRoundEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Round' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Round' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RoundIntegrationTest.testFlush() {
        fantasy.domain.Round obj = dod.getRandomRound();
        org.junit.Assert.assertNotNull("Data on demand for 'Round' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Round' failed to provide an identifier", id);
        obj = fantasy.domain.Round.findRound(id);
        org.junit.Assert.assertNotNull("Find method for 'Round' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRound(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Round' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RoundIntegrationTest.testMerge() {
        fantasy.domain.Round obj = dod.getRandomRound();
        org.junit.Assert.assertNotNull("Data on demand for 'Round' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Round' failed to provide an identifier", id);
        obj = fantasy.domain.Round.findRound(id);
        boolean modified =  dod.modifyRound(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        fantasy.domain.Round merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Round' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RoundIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Round' failed to initialize correctly", dod.getRandomRound());
        fantasy.domain.Round obj = dod.getNewTransientRound(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Round' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Round' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Round' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RoundIntegrationTest.testRemove() {
        fantasy.domain.Round obj = dod.getRandomRound();
        org.junit.Assert.assertNotNull("Data on demand for 'Round' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Round' failed to provide an identifier", id);
        obj = fantasy.domain.Round.findRound(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Round' with identifier '" + id + "'", fantasy.domain.Round.findRound(id));
    }
    
}
