// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fantasy.domain;

import fantasy.domain.Round;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect RoundDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RoundDataOnDemand: @Component;
    
    private Random RoundDataOnDemand.rnd = new SecureRandom();
    
    private List<Round> RoundDataOnDemand.data;
    
    public Round RoundDataOnDemand.getNewTransientRound(int index) {
        Round obj = new Round();
        setEndDate(obj, index);
        setName(obj, index);
        setStartDate(obj, index);
        return obj;
    }
    
    public void RoundDataOnDemand.setEndDate(Round obj, int index) {
        Date endDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setEndDate(endDate);
    }
    
    public void RoundDataOnDemand.setName(Round obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void RoundDataOnDemand.setStartDate(Round obj, int index) {
        Date startDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setStartDate(startDate);
    }
    
    public Round RoundDataOnDemand.getSpecificRound(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Round obj = data.get(index);
        return Round.findRound(obj.getId());
    }
    
    public Round RoundDataOnDemand.getRandomRound() {
        init();
        Round obj = data.get(rnd.nextInt(data.size()));
        return Round.findRound(obj.getId());
    }
    
    public boolean RoundDataOnDemand.modifyRound(Round obj) {
        return false;
    }
    
    public void RoundDataOnDemand.init() {
        data = Round.findRoundEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Round' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<fantasy.domain.Round>();
        for (int i = 0; i < 10; i++) {
            Round obj = getNewTransientRound(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
