// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fantasy.domain;

import fantasy.domain.Rules;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect RulesDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RulesDataOnDemand: @Component;
    
    private Random RulesDataOnDemand.rnd = new SecureRandom();
    
    private List<Rules> RulesDataOnDemand.data;
    
    public Rules RulesDataOnDemand.getNewTransientRules(int index) {
        Rules obj = new Rules();
        setText(obj, index);
        return obj;
    }
    
    public void RulesDataOnDemand.setText(Rules obj, int index) {
        String text = "text_" + index;
        obj.setText(text);
    }
    
    public Rules RulesDataOnDemand.getSpecificRules(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Rules obj = data.get(index);
        return Rules.findRules(obj.getId());
    }
    
    public Rules RulesDataOnDemand.getRandomRules() {
        init();
        Rules obj = data.get(rnd.nextInt(data.size()));
        return Rules.findRules(obj.getId());
    }
    
    public boolean RulesDataOnDemand.modifyRules(Rules obj) {
        return false;
    }
    
    public void RulesDataOnDemand.init() {
        data = Rules.findRulesEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Rules' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<fantasy.domain.Rules>();
        for (int i = 0; i < 10; i++) {
            Rules obj = getNewTransientRules(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
