// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fantasy.domain;

import fantasy.domain.RulesDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RulesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RulesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RulesIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: RulesIntegrationTest: @Transactional;
    
    @Autowired
    private RulesDataOnDemand RulesIntegrationTest.dod;
    
    @Test
    public void RulesIntegrationTest.testCountRuleses() {
        org.junit.Assert.assertNotNull("Data on demand for 'Rules' failed to initialize correctly", dod.getRandomRules());
        long count = fantasy.domain.Rules.countRuleses();
        org.junit.Assert.assertTrue("Counter for 'Rules' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RulesIntegrationTest.testFindRules() {
        fantasy.domain.Rules obj = dod.getRandomRules();
        org.junit.Assert.assertNotNull("Data on demand for 'Rules' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Rules' failed to provide an identifier", id);
        obj = fantasy.domain.Rules.findRules(id);
        org.junit.Assert.assertNotNull("Find method for 'Rules' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Rules' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RulesIntegrationTest.testFindAllRuleses() {
        org.junit.Assert.assertNotNull("Data on demand for 'Rules' failed to initialize correctly", dod.getRandomRules());
        long count = fantasy.domain.Rules.countRuleses();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Rules', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<fantasy.domain.Rules> result = fantasy.domain.Rules.findAllRuleses();
        org.junit.Assert.assertNotNull("Find all method for 'Rules' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Rules' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RulesIntegrationTest.testFindRulesEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Rules' failed to initialize correctly", dod.getRandomRules());
        long count = fantasy.domain.Rules.countRuleses();
        if (count > 20) count = 20;
        java.util.List<fantasy.domain.Rules> result = fantasy.domain.Rules.findRulesEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Rules' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Rules' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RulesIntegrationTest.testFlush() {
        fantasy.domain.Rules obj = dod.getRandomRules();
        org.junit.Assert.assertNotNull("Data on demand for 'Rules' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Rules' failed to provide an identifier", id);
        obj = fantasy.domain.Rules.findRules(id);
        org.junit.Assert.assertNotNull("Find method for 'Rules' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRules(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Rules' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RulesIntegrationTest.testMerge() {
        fantasy.domain.Rules obj = dod.getRandomRules();
        org.junit.Assert.assertNotNull("Data on demand for 'Rules' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Rules' failed to provide an identifier", id);
        obj = fantasy.domain.Rules.findRules(id);
        boolean modified =  dod.modifyRules(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        fantasy.domain.Rules merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Rules' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RulesIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Rules' failed to initialize correctly", dod.getRandomRules());
        fantasy.domain.Rules obj = dod.getNewTransientRules(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Rules' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Rules' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Rules' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RulesIntegrationTest.testRemove() {
        fantasy.domain.Rules obj = dod.getRandomRules();
        org.junit.Assert.assertNotNull("Data on demand for 'Rules' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Rules' failed to provide an identifier", id);
        obj = fantasy.domain.Rules.findRules(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Rules' with identifier '" + id + "'", fantasy.domain.Rules.findRules(id));
    }
    
}
