// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fantasy.domain;

import fantasy.domain.Team;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect TeamDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TeamDataOnDemand: @Component;
    
    private Random TeamDataOnDemand.rnd = new SecureRandom();
    
    private List<Team> TeamDataOnDemand.data;
    
    public Team TeamDataOnDemand.getNewTransientTeam(int index) {
        Team obj = new Team();
        setName(obj, index);
        return obj;
    }
    
    public void TeamDataOnDemand.setName(Team obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Team TeamDataOnDemand.getSpecificTeam(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Team obj = data.get(index);
        return Team.findTeam(obj.getId());
    }
    
    public Team TeamDataOnDemand.getRandomTeam() {
        init();
        Team obj = data.get(rnd.nextInt(data.size()));
        return Team.findTeam(obj.getId());
    }
    
    public boolean TeamDataOnDemand.modifyTeam(Team obj) {
        return false;
    }
    
    public void TeamDataOnDemand.init() {
        data = Team.findTeamEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Team' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<fantasy.domain.Team>();
        for (int i = 0; i < 10; i++) {
            Team obj = getNewTransientTeam(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
