// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fantasy.domain;

import fantasy.domain.UserClassDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserClassIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserClassIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserClassIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: UserClassIntegrationTest: @Transactional;
    
    @Autowired
    private UserClassDataOnDemand UserClassIntegrationTest.dod;
    
    @Test
    public void UserClassIntegrationTest.testCountUserClasses() {
        org.junit.Assert.assertNotNull("Data on demand for 'UserClass' failed to initialize correctly", dod.getRandomUserClass());
        long count = fantasy.domain.UserClass.countUserClasses();
        org.junit.Assert.assertTrue("Counter for 'UserClass' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserClassIntegrationTest.testFindUserClass() {
        fantasy.domain.UserClass obj = dod.getRandomUserClass();
        org.junit.Assert.assertNotNull("Data on demand for 'UserClass' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'UserClass' failed to provide an identifier", id);
        obj = fantasy.domain.UserClass.findUserClass(id);
        org.junit.Assert.assertNotNull("Find method for 'UserClass' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'UserClass' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UserClassIntegrationTest.testFindAllUserClasses() {
        org.junit.Assert.assertNotNull("Data on demand for 'UserClass' failed to initialize correctly", dod.getRandomUserClass());
        long count = fantasy.domain.UserClass.countUserClasses();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'UserClass', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<fantasy.domain.UserClass> result = fantasy.domain.UserClass.findAllUserClasses();
        org.junit.Assert.assertNotNull("Find all method for 'UserClass' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'UserClass' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserClassIntegrationTest.testFindUserClassEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'UserClass' failed to initialize correctly", dod.getRandomUserClass());
        long count = fantasy.domain.UserClass.countUserClasses();
        if (count > 20) count = 20;
        java.util.List<fantasy.domain.UserClass> result = fantasy.domain.UserClass.findUserClassEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'UserClass' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'UserClass' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserClassIntegrationTest.testFlush() {
        fantasy.domain.UserClass obj = dod.getRandomUserClass();
        org.junit.Assert.assertNotNull("Data on demand for 'UserClass' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'UserClass' failed to provide an identifier", id);
        obj = fantasy.domain.UserClass.findUserClass(id);
        org.junit.Assert.assertNotNull("Find method for 'UserClass' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUserClass(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'UserClass' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserClassIntegrationTest.testMerge() {
        fantasy.domain.UserClass obj = dod.getRandomUserClass();
        org.junit.Assert.assertNotNull("Data on demand for 'UserClass' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'UserClass' failed to provide an identifier", id);
        obj = fantasy.domain.UserClass.findUserClass(id);
        boolean modified =  dod.modifyUserClass(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        fantasy.domain.UserClass merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'UserClass' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserClassIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'UserClass' failed to initialize correctly", dod.getRandomUserClass());
        fantasy.domain.UserClass obj = dod.getNewTransientUserClass(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'UserClass' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'UserClass' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'UserClass' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UserClassIntegrationTest.testRemove() {
        fantasy.domain.UserClass obj = dod.getRandomUserClass();
        org.junit.Assert.assertNotNull("Data on demand for 'UserClass' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'UserClass' failed to provide an identifier", id);
        obj = fantasy.domain.UserClass.findUserClass(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'UserClass' with identifier '" + id + "'", fantasy.domain.UserClass.findUserClass(id));
    }
    
}
