// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fantasy.domain;

import java.lang.String;

privileged aspect News_Roo_JavaBean {
    
    public String News.getText() {
        return this.text;
    }
    
    public void News.setText(String text) {
        this.text = text;
    }
    
}
