// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fantasy.domain;

import java.lang.String;

privileged aspect Rules_Roo_JavaBean {
    
    public String Rules.getText() {
        return this.text;
    }
    
    public void Rules.setText(String text) {
        this.text = text;
    }
    
}
